### PR TITLE
ids for testing

### PR DESCRIPTION
**Pull request by danPudwellUK**
added id’s for automated testing

### CODE REVIEW

**Comment by timsb** [comment]
@danPudwellOpencast You have an ID on the parent element. Could you use that and then use the elements or classes within?

**Comment by danPudwellUK** [comment]
going to look into this...

**Comment by feedmypixel** [comment]
@danPudwellOpencast 

> going to look into this...

what happened with this?

**Comment by feedmypixel** [comment]
This is almost a year old - please reopen if still needed

**Pull request closed without merging**
