### PR TITLE
MTA-704 - Updates to attorney banner template and messages following integration with PTA.

### PR DESCRIPTION
**Pull request by michaeljcrossman**

### CODE REVIEW

**Comment by xnejp03** [comment]
These changes are custom for pertax application, but this component is common.

We should not pass any booleans to drive behaviour anymore, instead we now compose templates from bits of HTML. In your case it's probably easiest to have your own attorney banner in your app and provide that to the main template as the HTML snippet.

**Comment by michaeljcrossman** [comment]
These changes aren't custom for PTA, they are needed for all services who are integrating with PTA and trusted helpers.  They are common design patterns.

**Comment by alexanderjamesking** [comment]
We shouldn't be passing booleans down through the templates, it's far better to pass a block of HTML to be rendered rather than adding conditional logic within the templates as the conditional approach results in convoluted code.

Which services will be integrating with PTA and require this banner change?

**Comment by harish-hurchurn** [comment]
Alex can you reopen this PR and let us have the discussion on this page and we can close the other PR.

**Comment by alexanderjamesking** [comment]
I don't have permission to re-open the PR

**Comment by harish-hurchurn** [comment]
Petyr do you have perms to re-open the issue so we can continue to discuss this on here and we can close the other PR which has been opened.

**Comment by harish-hurchurn** [comment]
Alex with regards to your previous question about which team(s) will be integrating with Pertax, there are a few teams. The teams are as follows:
- Car tax
- iForms
- Medical benefits
- Tax Estimates

With more teams to be integrating in the very near future

**Comment by alexanderjamesking** [comment]
Feel free to add me on Skype (same as my github username) and we can discuss on there.

**Comment by nicf82** [comment]
Ill pick this up

**Pull request closed without merging**
